FRANCHISE_STORE_NAMES = {
    'akin adesola',
    'auas valley',
    'auckland park',
    'b1 city',
    'bay west',
    'beacon bay',
    'bedfordview',
    'benmore',
    'blackheath',
    'blue hills',
    'bo - kaap (closed)',
    'boardwalk mall',
    'bp pnp 222 service station',
    'bp pnp 3 rivers',
    'bp pnp acornhoek',
    'bp pnp aero motors',
    'bp pnp airfield',
    'bp pnp akasia',
    'bp pnp akazia',
    'bp pnp arena park',
    'bp pnp atterbury value mart',
    'bp pnp azmuth motors',
    'bp pnp badger motors',
    'bp pnp bedfordview',
    'bp pnp berea (pta)',
    'bp pnp berea el',
    'bp pnp bergbron',
    'bp pnp beyers naude north',
    'bp pnp beyers naude oasis - so',
    'bp pnp birch road',
    'bp pnp birnam park',
    'bp pnp blue hills',
    'bp pnp blue route service stat',
    'bp pnp bluff',
    'bp pnp boschfontein',
    'bp pnp boulders',
    'bp pnp brentwood',
    'bp pnp brickfields',
    'bp pnp bridge auto louis trich',
    'bp pnp bridge view service sta',
    'bp pnp brighton motors',
    'bp pnp broadacres',
    'bp pnp bruma',
    'bp pnp bullion boulevard expre',
    'bp pnp capricorn',
    'bp pnp cargo motors',
    'bp pnp cascades service statio',
    'bp pnp centurion',
    'bp pnp charles street',
    'bp pnp chatsworth circle',
    'bp pnp chess service station',
    'bp pnp city west ss - church s',
    'bp pnp clocktower',
    'bp pnp cm fuels',
    'bp pnp disa service station',
    'bp pnp dobsonville',
    'bp pnp dorp street',
    'bp pnp drive in motors',
    'bp pnp dube village mall',
    'bp pnp durham',
    "bp pnp e'thembeni",
    'bp pnp ebony park',
    'bp pnp edenburg',
    'bp pnp edendale ss',
    'bp pnp edenvale north',
    'bp pnp el corro motors',
    'bp pnp eldo glen',
    'bp pnp elgin',
    'bp pnp empire road',
    'bp pnp fiveways ss',
    'bp pnp flora lake service stat',
    'bp pnp fountain ss',
    'bp pnp fourways',
    'bp pnp frikkie meyer boulevard',
    'bp pnp gallo manor',
    'bp pnp glenfair service statio',
    'bp pnp glynwood',
    'bp pnp gordons bay',
    'bp pnp grabouw',
    'bp pnp grayston drive',
    'bp pnp greenacres',
    'bp pnp hans strydom',
    'bp pnp hazelwood',
    'bp pnp heritage park',
    'bp pnp highway soshanguve',
    'bp pnp hout bay petrol filling',
    'bp pnp howick falls garage',
    'bp pnp hutton hyde park',
    'bp pnp igqagqa',
    'bp pnp jan van riebeeck ss - p',
    'bp pnp jean avenue',
    'bp pnp jeffreys bay',
    'bp pnp john ross',
    'bp pnp jr filling station',
    'bp pnp kathlehong',
    'bp pnp kensington',
    'bp pnp kiasha park',
    'bp pnp king',
    'bp pnp klipgat',
    'bp pnp klipriver road',
    'bp pnp kramerville',
    'bp pnp kyalami',
    'bp pnp la lucia ridge oasis',
    'bp pnp lambton service station',
    'bp pnp lansdowne',
    'bp pnp lavender express',
    'bp pnp letchworth',
    'bp pnp libradene',
    'bp pnp linden park',
    'bp pnp louis botha',
    'bp pnp m1 oasis',
    'bp pnp m2 denver',
    'bp pnp mabopane',
    'bp pnp mahube valley',
    'bp pnp makhaza (closed)',
    'bp pnp malibu motors',
    'bp pnp mamelodi gardens',
    'bp pnp manor garage',
    'bp pnp maponya (closed)',
    'bp pnp mashikoane service stat',
    'bp pnp maxwell drive (closed)',
    'bp pnp meadowlands',
    'bp pnp melrose arch',
    'bp pnp merriman',
    'bp pnp mhluzi',
    'bp pnp midas',
    'bp pnp midtown',
    'bp pnp midway motors',
    'bp pnp moloto city',
    'bp pnp monte',
    'bp pnp montwood motors',
    'bp pnp moore road service stat',
    'bp pnp motorama',
    'bp pnp motordeal',
    'bp pnp motorhaven',
    'bp pnp n2 george',
    'bp pnp ndlela taxi city',
    'bp pnp negota motors',
    'bp pnp new germany service sta',
    'bp pnp newlands',
    'bp pnp newmarket',
    'bp pnp nirvana',
    'bp pnp north rand road',
    "bp pnp o'reilly merry",
    'bp pnp old farm',
    'bp pnp olivedale',
    'bp pnp palm court fuels',
    'bp pnp palm service station',
    'bp pnp park drive',
    'bp pnp pinehurst',
    'bp pnp pinelands',
    'bp pnp president motors',
    'bp pnp prince george drive',
    'bp pnp promenade',
    'bp pnp protea glen motors',
    'bp pnp queenswood',
    'bp pnp r81',
    'bp pnp rabie ridge',
    'bp pnp rachel de beer',
    'bp pnp radiokop',
    'bp pnp raisethorpe',
    'bp pnp rametse motors',
    'bp pnp randburg',
    'bp pnp randhart',
    'bp pnp reservoir hills service',
    'bp pnp riverside',
    'bp pnp rivonia',
    'bp pnp rockys service station',
    'bp pnp rosmead',
    'bp pnp safarituine diensstasie',
    'bp pnp salt lake',
    'bp pnp sandown (temporarily cl',
    'bp pnp sebokeng mall',
    'bp pnp sibaya',
    'bp pnp simon vermooten',
    'bp pnp somerset road service s',
    'bp pnp soshanguve (temporary c',
    'bp pnp soweto highway motors',
    'bp pnp spaarwater',
    'bp pnp stanford road',
    'bp pnp stedmans',
    'bp pnp strubensvalley service',
    'bp pnp sujee motors',
    'bp pnp sunnyrock',
    'bp pnp teanong service station',
    'bp pnp the cradle',
    'bp pnp the village',
    'bp pnp therons motors',
    'bp pnp theta',
    'bp pnp thorntree',
    'bp pnp tom jones',
    'bp pnp tshepisong',
    'bp pnp twin palms',
    'bp pnp tygervalley',
    'bp pnp umlazi service station',
    'bp pnp val de grace',
    'bp pnp verulam',
    'bp pnp vosloorus',
    'bp pnp vrededorp',
    'bp pnp walmer gardens',
    'bp pnp waterfall',
    'bp pnp waterfall park',
    'bp pnp waterkloof ridge',
    'bp pnp waterloo',
    'bp pnp welgelee',
    'bp pnp westville autohouse',
    'bp pnp william nicol',
    'bp pnp wine route',
    'bp pnp winmore',
    'bp pnp zeerust',
    'brandwag (closed)',
    'bylsbridge promenade',
    'caledon mall',
    'camps bay',
    'canal crossing',
    'canal walk',
    'cape gate',
    'cape town dotcoza centre',
    'carletonville',
    'carnival mall',
    'cavendish',
    'cedar road',
    'centre point milnerton',
    'centro mall',
    'centurion',
    'century mall newcastle',
    'chilli lane',
    'chingola',
    'christians village',
    'city centre',
    'clanwilliam',
    'claremont',
    'clearwater mall',
    'cllothing morning glen mall',
    'clothing 14th ave constantia',
    'clothing access park',
    'clothing albermarle',
    'clothing alex mall',
    'clothing amajuba mall',
    'clothing athlone circle',
    'clothing atlas mall',
    'clothing atterbury',
    'clothing auckland park',
    'clothing autumn leaf mall',
    'clothing balfour centre',
    'clothing ballito junction',
    'clothing barberton jock of the',
    'clothing bassonia',
    'clothing baywest',
    'clothing beacon bay',
    'clothing bedford centre',
    'clothing bedford village',
    'clothing bel air',
    'clothing bela-bela',
    'clothing bells drive',
    'clothing ben fleur',
    'clothing benmore gardens',
    'clothing birchleigh north',
    'clothing blu bird',
    'clothing blu valley mall',
    'clothing blue route',
    'clothing boardwalk pe',
    'clothing bonearo park',
    'clothing boskruin village',
    'clothing bothasig',
    'clothing bredasdorp',
    'clothing brits mall',
    'clothing brooklyn',
    'clothing bryanston',
    'clothing caledon',
    'clothing canal walk',
    'clothing canterbury crossing s',
    'clothing cape gate',
    'clothing cape gate value',
    'clothing carnival mall',
    'clothing cascades',
    'clothing castle gate',
    'clothing cavendish',
    'clothing cedar square',
    'clothing centurion mall',
    'clothing ceres',
    'clothing chartwell corner',
    'clothing chilli lane',
    'clothing christians village',
    'clothing circle centre',
    'clothing clanwilliam',
    'clothing claremont',
    'clothing clearwater',
    'clothing cobble walk',
    'clothing columbine square',
    'clothing corkwood',
    'clothing cornubia',
    'clothing cornwall view',
    'clothing cosmo mall',
    'clothing cradlestone mall',
    'clothing cresta',
    'clothing crowthorne',
    'clothing dainfern square',
    'clothing darras centre',
    'clothing de bron - malmesbury',
    'clothing de zwartland mall',
    'clothing diamond pavilion',
    'clothing dihlabeng square',
    'clothing douglasdale',
    'clothing east rand mall',
    'clothing eastgate',
    'clothing eden meander',
    'clothing eden square',
    'clothing eerste rivier',
    'clothing eikestad',
    'clothing el ridge',
    'clothing elardus park',
    'clothing elgin mall',
    'clothing empangeni sanlam cent',
    'clothing ermelo mall',
    'clothing escourt mall',
    'clothing fairbridge mall',
    'clothing fairways on main (how',
    'clothing farramere',
    'clothing featherbrook',
    'clothing ferndale on republic',
    'clothing ferndale village',
    'clothing festival mall',
    'clothing flamingo',
    'clothing flamwood walk',
    'clothing fountains mall',
    'clothing fourways',
    'clothing fourways crossing',
    'clothing galleria',
    'clothing garden route mall (ge',
    'clothing gateway',
    'clothing gezina galleries',
    'clothing gift acres mall',
    'clothing glen marais',
    'clothing glen vista',
    'clothing glenfair boulevard',
    'clothing glengarry',
    'clothing goldfields',
    'clothing grayston centre',
    'clothing greenacres',
    'clothing greenstone',
    'clothing grey owl',
    'clothing groblersdal',
    'clothing haasendal gables',
    'clothing harbour bay',
    'clothing hartebeespoort',
    'clothing harvest place',
    'clothing hatfield plaza',
    'clothing hazeldean',
    'clothing hazyview junction',
    'clothing heathway',
    'clothing heidelberg mall',
    'clothing hemingways',
    'clothing heritage square',
    'clothing hermanus (closed)',
    'clothing highland mews',
    'clothing highveld',
    'clothing hillcrest boulevard',
    'clothing hilton the avenues',
    'clothing hoedspruit mall',
    'clothing honeydew village',
    'clothing horizon village',
    'clothing hout bay',
    'clothing howard centre',
    "clothing i'langa",
    'clothing irene',
    'clothing irene boulevard',
    'clothing jabulani mall (soweto',
    'clothing jacaranda',
    'clothing jackal creek',
    'clothing jean avenue',
    'clothing jubilee mall',
    'clothing junxion mall',
    'clothing kalahari mall',
    'clothing karaglen',
    'clothing kempton gate',
    'clothing kenilworth centre',
    'clothing key west',
    'clothing killarney mall',
    'clothing kings mall',
    'clothing kingsburgh mall',
    'clothing kloof',
    'clothing knysna',
    'clothing kokstad',
    'clothing kolonnade',
    'clothing kuruman',
    'clothing kwagga plaza',
    'clothing kyalami corner',
    'clothing la lucia',
    'clothing lady grey street',
    'clothing ladysmith',
    'clothing lakeside mall',
    'clothing lambton centre',
    'clothing langebaan',
    'clothing langeberg mall',
    'clothing lemon tree',
    'clothing lephalale mall',
    'clothing lichtenburg mall',
    'clothing life midlands',
    'clothing lifestyle crossing',
    'clothing lighthouse mall',
    'clothing loch logan',
    'clothing loftus park',
    'clothing lonehill',
    'clothing lorraine gardens',
    'clothing lowveld mall',
    'clothing madelief',
    'clothing malelane',
    'clothing mall @ 55',
    'clothing mall at reds',
    'clothing mall of africa',
    'clothing mall of the north',
    'clothing mall of the south',
    'clothing mall of thembisa',
    'clothing mamelodi square',
    'clothing mams mall',
    'clothing mayfield square',
    'clothing meadowdale',
    'clothing meer en see',
    'clothing melkbos',
    'clothing menlyn park',
    'clothing merinno mall',
    'clothing metlife plaza (closed',
    'clothing meyersdal',
    'clothing middelburg',
    'clothing midwater',
    'clothing midway crossing',
    'clothing midway mews',
    'clothing mimosa mall',
    'clothing modi mall',
    'clothing mompati mall',
    'clothing montclair crescent',
    'clothing mooirivier',
    'clothing moruleng mall',
    'clothing mossel bay',
    'clothing motlasana',
    'clothing mountain mill',
    'clothing musgrave',
    'clothing n1 city',
    'clothing neighbourhood square',
    'clothing new longbeach',
    'clothing new market',
    'clothing new redruth',
    'clothing new tokai',
    'clothing newcastle',
    'clothing nicolway',
    'clothing nina park',
    'clothing norkem',
    'clothing north cape mall',
    'clothing northcliff square',
    'clothing northgate shopping ce',
    'clothing northlands corner',
    'clothing northmead',
    'clothing northmead square',
    'clothing northridge',
    'clothing oakfields',
    "clothing ocean's mall",
    'clothing olympus village',
    'clothing online store',
    'clothing paarl village',
    'clothing paarlmall',
    'clothing parkrand plazza',
    'clothing parkview',
    'clothing parow',
    'clothing pavillion',
    'clothing penford centre',
    'clothing plantland',
    'clothing platinum square',
    'clothing plattekloof',
    'clothing plettenberg bay(marke',
    'clothing polo fields',
    'clothing pongola',
    'clothing preller square',
    'clothing president square',
    'clothing promenade centre',
    'clothing quagga',
    'clothing queens mall',
    'clothing queenswood',
    'clothing randridge mall',
    'clothing randstream shopping c',
    'clothing ravenswood',
    'clothing regent square',
    'clothing retail park boksburg',
    'clothing richards bay',
    'clothing richmond',
    'clothing ridgeview',
    'clothing river square',
    'clothing riverside boulevard',
    'clothing riverside centre',
    'clothing riverside mall',
    'clothing rivonia village',
    'clothing rosebank mall',
    'clothing rustenburg',
    'clothing rustenburg lifestyle',
    'clothing ryneveld lifestyle',
    'clothing rynfield centre',
    'clothing sable square',
    'clothing safari centre',
    'clothing sanbury square',
    'clothing sanctuary square',
    'clothing sandridge square',
    'clothing sandton city',
    'clothing sasolburg boulevard',
    'clothing savannah mall',
    'clothing saveway crescent',
    'clothing saxby eldoraigne vill',
    'clothing scottburgh',
    'clothing seadoone mall',
    'clothing sechaba mall',
    'clothing secunda mall',
    'clothing shelly beach centre',
    'clothing silver mall',
    'clothing silverwater crossing',
    'clothing sinoville shopping ce',
    'clothing sitari village',
    'clothing somerset mall',
    'clothing soneike',
    'clothing sonstraal',
    'clothing south coast mall',
    'clothing south east boulevard',
    'clothing southdowns',
    'clothing southgate',
    'clothing southway mall',
    'clothing springs mall',
    'clothing stonehill crossing',
    'clothing strand square',
    'clothing summerstrand village',
    'clothing sunningdale',
    'clothing sunninghill village',
    'clothing sunridge',
    'clothing sunward centre',
    'clothing sunward park',
    'clothing table bay mall',
    'clothing tablewview',
    'clothing tambotie',
    'clothing thaba mall',
    'clothing thabong shopping cent',
    'clothing thatchfield',
    'clothing thavhani mall',
    'clothing the angelo mall',
    'clothing the atrium (kzn)',
    'clothing the bluff',
    'clothing the conservatory',
    'clothing the crossing',
    'clothing the falls',
    'clothing the glen',
    'clothing the greenery',
    'clothing the grove',
    'clothing the islands',
    'clothing the paddocks',
    'clothing the rivershed',
    'clothing the towers lhp',
    'clothing the victorian',
    'clothing the village',
    'clothing three arts',
    'clothing times square (walmer)',
    'clothing trade route mall',
    'clothing tshwane mall',
    'clothing tyger valley',
    'clothing tzaneng mall',
    'clothing ulundi king centre',
    'clothing umhlanga crescent',
    'clothing umlazi mega city',
    'clothing vaal mall',
    'clothing valley hyper',
    'clothing valleyview',
    'clothing van riebeek mall',
    'clothing victory park',
    'clothing village market',
    'clothing vincent park',
    'clothing vredenburg',
    'clothing walker drive',
    'clothing walmer',
    'clothing watercrest mall',
    'clothing waterfall mall',
    'clothing waterstone village',
    'clothing waverly plaza',
    'clothing weskus mall',
    'clothing west acres',
    'clothing westgate mall mitchel',
    'clothing westwood mall',
    'clothing westwood village',
    'clothing whale coast mall',
    'clothing white river crossing',
    'clothing willowbridge',
    'clothing wilrogate shopping ce',
    'clothing windermere',
    'clothing wonderboom junction',
    'clothing woodburn',
    'clothing woodhill',
    'clothing woodlands',
    'clothing york street',
    'clothing zambezi junction',
    'clothing zevenview',
    'clothing zevenwacht',
    'coachmans crossing',
    'constantia',
    'cornubia',
    'cradlestone mall',
    'cresta',
    'dainfern square',
    'dihlabeng mall bethlehem',
    'douglasdale',
    'dunes',
    'durbanville',
    'express azmuth',
    "express e'thembeni",
    'express kwa mashu',
    'express lavender',
    'express midway motors',
    'express mile4',
    'express moloto city',
    'express soweto',
    'fairmount',
    'family aliwal north',
    'family ashburton (closed)',
    'family athlone circle',
    'family azaleapark',
    'family ballito',
    'family barberton',
    'family bethlehem',
    'family beyers naude',
    'family birchleigh',
    'family bonaero park',
    'family brackenfell',
    'family brackenhurst',
    'family bramley',
    'family bredasdorp',
    'family brentwood park',
    'family brits',
    'family brits mall',
    'family brixton',
    'family bronkhorstspruit',
    'family ceres',
    'family christian village (hillcrest)',
    'family circle centre',
    'family cleary park',
    'family coachmans crossing(clos',
    'family cornwall view',
    'family cradlestone mall',
    'family craighall park',
    'family crescent',
    'family cycad',
    'family dairy',
    'family delmas',
    'family despatch',
    'family despatch liquor store',
    'family dorandia',
    'family douglasdale (closed)',
    'family dundee',
    'family edenglen',
    'family edenvale',
    'family eersterust',
    'family elgin',
    'family elspark',
    'family epsom downs',
    'family equestria mall',
    'family ermelo',
    'family eshowe',
    'family essenwood',
    'family essenwood liquor',
    'family estcourt',
    'family ezulwini',
    'family farramere',
    'family ferndale on republic',
    'family fish hoek',
    'family fleurdal',
    'family fluerdal',
    'family fountains mall',
    'family fraaiuitsig',
    'family francistown 1',
    'family francistown two',
    'family franschhoek',
    'family frost street',
    'family gables clothing',
    'family george',
    'family glen marais',
    'family golf park',
    'family gordons bay',
    'family graaff-reinet',
    'family graanendal',
    'family grahamstown',
    'family greenfields',
    'family groot brak',
    'family harrismith',
    'family hartenbos',
    'family hartenbos strandoord',
    'family harties',
    'family hazelpark',
    'family heidelberg',
    'family heugh road',
    'family hillside',
    'family hoedspruit',
    'family honey junction',
    'family hoopstad',
    'family hub clothing',
    'family jwaneng mall',
    'family kathu',
    'family kelvin',
    'family kemptongate',
    'family kilburn (closed)',
    'family kilburn liquor',
    'family king williams town',
    'family kingsburgh',
    'family kirstens',
    'family kloof',
    'family knowles',
    'family kokstad',
    'family kraaifontein',
    'family kroonstad',
    'family kuilsriver',
    'family kuruman two',
    'family lakefield',
    'family lambton',
    'family langebaan',
    'family langehovenpark (closed)',
    'family lephalale',
    'family lephalale square',
    'family linton corner',
    'family linton grange',
    'family lobatse',
    'family lydenburg',
    'family mafikeng crossing',
    'family magalieskruin',
    'family makana',
    'family malelane',
    'family malkerns',
    'family malmesbury',
    'family manzini',
    'family mashayitafula',
    'family mashyitafula liquor',
    'family matsapha',
    'family matsapha link',
    'family matsapha link clothing',
    'family matsapha liquor wholesa',
    'family mbabane',
    'family meyerton',
    'family midway mews',
    'family mini market bethlehem',
    'family modimolle',
    'family mtubatuba',
    'family mulbarton park',
    'family newcastle',
    'family newmarket',
    'family newton park',
    'family nhlangano',
    'family northcliff square',
    'family northmead mall',
    'family nowles',
    'family nowles liquor',
    'family oakdene',
    'family oakfields',
    'family observatory',
    'family odensdaalsrus',
    'family oudtshoorn',
    'family outspan road',
    'family pacaltsdorp',
    'family panorama',
    'family parow',
    'family parys',
    'family phalaborwa',
    'family phikwe mall',
    'family piet retief',
    'family pietermaritzburg',
    'family pine ridge',
    'family pioneer park',
    'family plettenberg bay',
    'family plumstead',
    'family pollyshorts liquor (clo',
    'family pongola',
    'family port alfred',
    'family port shepstone',
    'family preller walk mall',
    'family pretoria north',
    'family queenstown',
    'family randfontein (closed)',
    'family rayton',
    'family reizis',
    'family reizis square',
    'family reyno ridge',
    'family rhodesdene',
    'family riebeek wes',
    'family river crescent',
    'family river park',
    'family river stone',
    'family river walk gabarone',
    'family riversdale (closed)',
    'family robertson',
    'family rondebosch',
    'family sable square',
    'family sandridge square',
    'family sarona',
    'family sasolburg',
    'family scottburgh cbd (closed)',
    'family sebele',
    'family secunda',
    'family sedgefield',
    'family sharon park',
    'family sherwood',
    'family silverwater crossing',
    'family simons town',
    'family sky city',
    'family songloed',
    'family springs gate',
    'family st. johns village',
    'family standerton',
    'family standerton liquor',
    'family stanger',
    'family steenberg',
    'family stonehill crossing',
    'family strand street',
    'family strubenvale',
    'family struisbaai',
    'family struisbaai liquor',
    'family stutterheim',
    'family summerfields boskruin',
    'family swellendam',
    'family tembisa megamart',
    'family thaba mall',
    'family the avenue hilton',
    'family the galleria',
    'family the gardens',
    'family the reeds',
    'family the reeds liquor',
    'family the verge',
    'family towers',
    'family towers at lan',
    'family towers at langenhoven',
    'family umhlanga',
    'family upington',
    'family van riebeeck park',
    'family vanderbijl',
    'family vanderbijl park',
    'family vanderhof park',
    'family verulam',
    'family vredenburg',
    'family vryburg',
    'family vryheid',
    'family walker drive',
    'family warmbaths',
    'family waverly',
    'family welkom',
    'family wellington',
    'family westonaria',
    'family westville junction',
    'family whiteriver',
    'family willowbridge',
    'family wilro park',
    'family witbank',
    'family witpoortjie',
    'family wolmaransstad',
    'family wonderboom junction',
    'family woodlands boulevard',
    'family york street',
    'family zeerust',
    'famly rhodesdene',
    'florida',
    'fourways',
    'fourways mall',
    'foxdale',
    'gallo manor',
    'garden city',
    'garden house',
    'garden route mall',
    'gardens',
    'george',
    'gezina',
    'glen garry',
    'glover road',
    'gonubie',
    'grahamstown liquor store',
    'grootfontein',
    'hayfields',
    'hazeldean square',
    'hemingways',
    'hermanus',
    'highveld mall',
    'hillcrest boulevard',
    'hout bay',
    'hyde park',
    'hyper bloemfontein',
    'hyper boksburg',
    'hyper brackenfell',
    'hyper centurion',
    'hyper durban north',
    'hyper faerie glen',
    'hyper greenstone',
    'hyper klerksdorp',
    'hyper moffet',
    'hyper montana',
    'hyper northgate',
    'hyper norwood',
    'hyper ottery',
    'hyper princess crossing',
    'hyper south coast',
    'hyper steeledale',
    'hyper vaal (closed)',
    'hyper witbank',
    'hyper woodmead',
    'ilanga mall',
    'irene village mall',
    'jean avenue',
    'kafue',
    'kansenshi',
    'kapiji',
    'katima mulilo',
    'katutura',
    'kenilworth',
    'kenilworth campus',
    'kensington',
    'kensington campus store (close',
    'key west',
    'kilburn',
    'killarney',
    'kitwe city centre',
    'knysna',
    'krugersdorp',
    'kyalami on main',
    'la lucia',
    'ladysmith',
    'lakeside',
    'langeberg mall',
    'langehoven park',
    'lenasia',
    'lephalale',
    'levy',
    'linden lanes',
    'linton corner',
    'local big bay',
    'local boston',
    'local bredasdorp (closed)',
    'local cherry lane (closed)',
    'local eastdale',
    'local glen curve',
    'local golding on main',
    'local kenridge',
    'local monte vista',
    'local moreleta park',
    'local morningside florida road',
    'local petervale',
    'local polokwane crescent',
    'local ridge terrace',
    'local senderwood (closed)',
    'local station house sea point',
    'local waterglen',
    'local welgemoed',
    'loch logan',
    'lonehill',
    'long acres',
    'longbeach mall',
    'luanshya',
    'lynnwood',
    'makeni',
    'makhado',
    'mall at reds',
    'mall of africa',
    'mall of the north',
    'mall of the south',
    'margate',
    "market bassiane's",
    'market bra todd',
    "market bvn's (closed)",
    "market dinny's (closed)",
    'market dmrg (closed)',
    'market easyway (closed)',
    'market eden park (closed)',
    'market glenridge',
    'market joy (closed)',
    'market kayleah (closed)',
    'market kwazikode (clossed)',
    "market lebo's (closed)",
    "market linda's (closed)",
    'market makhetha (closed)',
    'market masha (closed)',
    'market matjeke',
    'market mbekweni (closed)',
    'market mnandilit (closed)',
    'market monageng',
    'market nabe (closed)',
    'market ndofaya (closed)',
    'market ndwamba',
    "market ola's",
    "market ola's 2",
    'market palti (closed)',
    "market peso's (closed)",
    "market peso's 2 (clossed)",
    'market pilgrims corner (closed',
    'market proper liquor (closed)',
    "market sechabisto's (closed)",
    'market something nice (closed)',
    'market summore (closed)',
    'market wabos (closed)',
    'meer en see',
    'mega centre',
    'melkbos',
    'memorial park',
    'menlyn maine',
    'menlyn mall',
    'merino mall ermelo',
    'middelburg mall',
    'midlands mall',
    'midwater middleburg',
    'mini market aston manor',
    'mini market bethlehem',
    'mini market fourways',
    'mini market golf park',
    'mini market henneman',
    'mini market lakefield',
    'mini market oakdene',
    'mini market randfontein',
    'mini market riebeeck kasteel',
    'mini market showgrounds',
    'mini market viljoenskroon',
    'mini market virginia',
    'mokopane mall',
    'montana',
    'morningside',
    'mountain mill',
    'mukuba mall',
    'mulbarton',
    'musgrave road',
    'n1 city',
    'nelspruit',
    'new red ruth',
    'newton park',
    'noordstad',
    'northlands corner',
    'northrise',
    'okahandja',
    'okongo',
    'olunkono',
    'olympus',
    'on nicol',
    'ondangwa',
    'oshakati',
    'oshana',
    'oshikango ii',
    'outapi',
    'paarl mall',
    'parklands',
    'pecanwood',
    'phi',
    "pick 'n pay maseru",
    'picknpay masianokeng',
    'pinehurst',
    'pinelands',
    'pineslopes boulevard (fourways',
    'plantland boardway',
    'plattekloof',
    'pnp doringkloof',
    'pnp family verulam',
    'pnp hyper qualisave soweto',
    'pnp hyper qualisave wonderpark',
    'pnp hyper somerset mall',
    'pnp qualisave alberton city',
    'pnp qualisave alex mall',
    'pnp qualisave atteridgeville',
    'pnp qualisave bethlehem',
    "pnp qualisave birch acre's",
    'pnp qualisave bluewater bay',
    'pnp qualisave bophelong',
    'pnp qualisave botshabelo',
    'pnp qualisave braamfontein',
    'pnp qualisave burgersfort tuba',
    'pnp qualisave bushbuckridge',
    'pnp qualisave busy corner / eb',
    'pnp qualisave carletonville ma',
    'pnp qualisave carlton centre',
    'pnp qualisave chatsworth',
    'pnp qualisave chris hani cross',
    'pnp qualisave cleary park',
    'pnp qualisave commercial road',
    'pnp qualisave cosmo city',
    'pnp qualisave cosmo mall',
    'pnp qualisave darras',
    'pnp qualisave daveyton',
    'pnp qualisave die meent',
    'pnp qualisave diepkloof',
    'pnp qualisave diepsloot',
    'pnp qualisave dobsonville',
    'pnp qualisave eersteriver',
    'pnp qualisave embalenhle',
    'pnp qualisave emoyeni',
    'pnp qualisave empangeni',
    'pnp qualisave epping gardens',
    'pnp qualisave evaton',
    'pnp qualisave festival mall',
    'pnp qualisave forest hill(clos',
    'pnp qualisave ga-rankuwa',
    'pnp qualisave galeshewe',
    'pnp qualisave galeshewe-kimber',
    'pnp qualisave germiston (close',
    'pnp qualisave giyani',
    'pnp qualisave goodwood',
    'pnp qualisave grabouw',
    'pnp qualisave groblersdal',
    'pnp qualisave groendal',
    'pnp qualisave hatfield',
    'pnp qualisave hibberdene',
    'pnp qualisave jabulani mall',
    'pnp qualisave jackal creek',
    'pnp qualisave jane furse',
    'pnp qualisave jubilee mall',
    'pnp qualisave kempton square',
    'pnp qualisave khayelitsha',
    'pnp qualisave kimberley cbd',
    'pnp qualisave kroonstad',
    'pnp qualisave kwa-guqa',
    'pnp qualisave kwadukuza mall',
    'pnp qualisave kwagga plaza',
    'pnp qualisave lakeside mall',
    'pnp qualisave lebo mall',
    'pnp qualisave lemo mall',
    'pnp qualisave letsheng mall',
    'pnp qualisave local atlantis',
    'pnp qualisave local bloem plaz',
    'pnp qualisave local bloemgate',
    'pnp qualisave local chamdoor k',
    'pnp qualisave local ficksburg',
    'pnp qualisave local germiston',
    'pnp qualisave local golden sun',
    'pnp qualisave local goldman st',
    'pnp qualisave local grassy par',
    'pnp qualisave local halt road',
    'pnp qualisave local hazyview',
    'pnp qualisave local hendrina',
    'pnp qualisave local klipkop de',
    'pnp qualisave local leandra',
    'pnp qualisave local leondale r',
    'pnp qualisave local lotus rive',
    'pnp qualisave local louis both',
    'pnp qualisave local north beac',
    'pnp qualisave local northam',
    'pnp qualisave local palm ridge',
    'pnp qualisave local palm sprin',
    'pnp qualisave local poppys ret',
    'pnp qualisave local victoria r',
    'pnp qualisave local worcester',
    'pnp qualisave mabopane',
    'pnp qualisave mabopane lifesty',
    'pnp qualisave maitland',
    'pnp qualisave maluti crescent',
    'pnp qualisave mamelodi mall',
    'pnp qualisave matatiele',
    'pnp qualisave matlosana mall k',
    'pnp qualisave mayfield square',
    'pnp qualisave mdantsane city',
    'pnp qualisave meadowlands',
    'pnp qualisave middestad(closed',
    'pnp qualisave midrand',
    'pnp qualisave midway crossing',
    'pnp qualisave mmbatho',
    'pnp qualisave montclair',
    'pnp qualisave mooi river',
    'pnp qualisave moruleng mall',
    'pnp qualisave mthatha mall',
    'pnp qualisave muizenberg',
    'pnp qualisave newcastle scott',
    'pnp qualisave newtown junction',
    'pnp qualisave nkomazi plaza',
    'pnp qualisave nkomo mall',
    'pnp qualisave nonesi mall',
    'pnp qualisave one on mutual',
    'pnp qualisave orange farm - ey',
    'pnp qualisave parklands juncti',
    'pnp qualisave parow exchange',
    'pnp qualisave philip nel',
    'pnp qualisave phillipi',
    'pnp qualisave phoenix liquor (',
    'pnp qualisave piet retief dowt',
    'pnp qualisave pinetown',
    'pnp qualisave polokwane (piete',
    'pnp qualisave postmasburg',
    'pnp qualisave promenade',
    'pnp qualisave protea boulevard',
    'pnp qualisave protea north',
    'pnp qualisave quagga',
    'pnp qualisave ram square',
    'pnp qualisave randburg square',
    'pnp qualisave richards bay',
    'pnp qualisave rustenburg',
    'pnp qualisave sam ntuli mall',
    'pnp qualisave sasolburg',
    'pnp qualisave soshanguve crossing',
    'pnp qualisave southdale',
    'pnp qualisave southernwood',
    'pnp qualisave southgate',
    'pnp qualisave springfield',
    'pnp qualisave standerton cbd',
    'pnp qualisave steelpoort',
    'pnp qualisave steelpoort liquo',
    'pnp qualisave sunnyside (sterl',
    'pnp qualisave tembisa',
    'pnp qualisave tembisa mega mar',
    'pnp qualisave thabong mall (se',
    'pnp qualisave thavhani',
    'pnp qualisave the bridge',
    'pnp qualisave the oaks',
    'pnp qualisave the workshop',
    'pnp qualisave thlabane mall',
    'pnp qualisave thulamahashe',
    'pnp qualisave top spot (closed',
    'pnp qualisave tramshed',
    'pnp qualisave tshepisong',
    'pnp qualisave tshwane mall',
    'pnp qualisave tzaneen',
    'pnp qualisave uitenhage cbd',
    'pnp qualisave umlazi kwa-mnyan',
    'pnp qualisave umlazi mega city',
    'pnp qualisave umphakathi',
    'pnp qualisave umtata',
    'pnp qualisave vaalbank',
    'pnp qualisave vangate mall',
    'pnp qualisave vereeniging',
    'pnp qualisave vosloorus',
    'pnp qualisave westgate',
    'pnp qualisave wynberg',
    "pnp qualisave@dj's (closed)",
    "pnp qualisave@dj's liquor (clo",
    'pnp swellendam',
    'pnp teemane',
    'potchefstroom',
    'primrose',
    'queensburgh',
    'rand steam',
    'randpark ridge',
    'ravenswood',
    'richmond corner',
    'riverside mall',
    'rockville market',
    'rosebank',
    'rosmead',
    'royldene',
    'ruimsig',
    'rundu',
    'sanbury square',
    'savannah',
    'scottburgh',
    'sea point',
    'secunda mall',
    'shelly beach',
    'sinoville',
    'society house',
    'somerset west',
    'southdowns',
    'springs mall',
    'stellenbosch',
    'stellenbosch square',
    'strand',
    'summerstrand',
    'sunningdale',
    'sunward park',
    'swakopmund',
    'table bay mall',
    'tableview',
    'the 3 arts diep river',
    'the avenues hilton',
    'the bluff',
    'the falls',
    'the fields',
    'the glen',
    'the grove',
    'the marc',
    'the pavilion',
    'the sanctuary strand',
    'three rivers',
    'tokai',
    'toro junction',
    'tsumeb mall',
    'tygervalley',
    'uitenhage',
    'umhlanga crescent',
    'vaal mall',
    'victory park',
    'vincent park',
    'walmer park',
    'waterfall mall',
    'waterfront',
    'waterkloof',
    'waterstone village',
    'welkom',
    'wernhill',
    'weskus mall',
    'westwood',
    'wholesale brackenfell',
    'wholesale durban',
    'wholesale klerksdorp',
    'wholesale steeledale',
    'wholesale william moffet',
    'wholesale wonderpark',
    'wonderboom junction',
    'woodlands',
    'woodlands boulevard',
    'worcester',
    'zevenview',
}

CORPORATE_STORE_NAMES = {
    'alberton city',
    'alex mall',
    'atlantis',
    'atteridgeville maunde street',
    'auckland park',
    'bay west',
    'beacon bay',
    'bedfordview',
    'benmore',
    'bethlehem',
    'blackheath',
    'blue hills',
    'boardwalk',
    'boardwalk richards bay',
    'botshabelo',
    'burgersfort tubatse crossing',
    'bylsbridge promenade',
    'caledon mall',
    'camps bay',
    'canal crossing',
    'canal walk',
    'cape gate',
    'carletonville',
    'carletonville mall',
    'carnival mall',
    'cavendish',
    'cedar road',
    'centre point',
    'centurion',
    'century mall newcastle',
    'chamdor kagiso',
    'chatsworth',
    'chilli lane',
    'chris hani crossing',
    'christians village',
    'clanwilliam',
    'claremont',
    'clearwater mall',
    'cleary park',
    'coachmans crossing',
    'commercial road',
    'constantia',
    'cornubia',
    'cosmo mall',
    'cradlestone mall',
    'cresta',
    'dainfern square',
    'daveyton',
    'die meent',
    'diepkloof',
    'diepsloot',
    'dihlabeng mall bethlehem',
    'dobsonville mall',
    'doornkloof',
    'douglasdale',
    'durbanville',
    'eerste riviers',
    'embalenhle',
    'emoyeni',
    'empangeni',
    'ermelo',
    'faerie glen hyper',
    'fairmount',
    'family aliwal north',
    'family athlone circle',
    'family atteridgeville mareka stree',
    'family azaleapark',
    'family ballito',
    'family barberton',
    'family beyers naude',
    'family birchacres',
    'family bophelong',
    'family braamfontein',
    'family brackenfell',
    'family brackenhurst',
    'family bramley',
    'family bredasdorp',
    'family brits',
    'family brits mall',
    'family brixton',
    'family bronkhorstspruit',
    'family bushbuckridge',
    'family busy corner',
    'family ceres',
    'family christian village',
    'family church street (piet ret',
    'family circle centre',
    'family cleary park',
    'family cornwall view',
    'family cosmo city',
    'family cradlestone mall',
    'family cycad',
    'family delmas',
    'family despatch',
    'family dorandia',
    'family dundee',
    'family eersterust',
    'family elspark',
    'family epsom downs',
    'family equestria mall',
    'family eshowe',
    'family essenwood',
    'family estcourt',
    'family evaton',
    'family eyethu mall',
    'family farramere',
    'family ferndale on republic',
    'family fish hoek',
    'family fluerdal',
    'family fountains mall',
    'family fraaiuitsig',
    'family franschhoek',
    'family frost street',
    'family ga rankuwa mall',
    'family galeshewe',
    'family george',
    'family gordons bay',
    'family graaff-reinet',
    'family graanendal',
    'family grahamstown',
    'family greenfields',
    'family harrismith',
    'family hartenbos strandoord',
    'family harties',
    'family hazelpark',
    'family heidelberg',
    'family heugh road',
    'family hilton avenues',
    'family hoedspruit',
    'family honey junction',
    'family hoopstad',
    'family jackal creek',
    'family jane furse',
    'family kathu',
    'family kempton square',
    'family khayelitsha',
    'family king williams town',
    'family kingsburgh',
    'family kloof',
    'family kokstad',
    'family kraaifontein',
    'family kroonstad',
    'family kuilsriver',
    'family kuruman two',
    'family lambton',
    'family langebaan',
    'family lephalale',
    'family lephalale square',
    'family linton corner',
    'family linton grange',
    'family lydenburg',
    'family mafikeng crossing',
    'family magalieskruin',
    'family makana',
    'family malelane',
    'family malmesbury',
    'family mdantsane',
    'family meadowlands',
    'family meyerton',
    'family midway mews',
    'family modimolle',
    'family mulbarton park',
    'family newcastle',
    'family newmarket',
    'family newton park',
    'family nkomazi plaza',
    'family northcliff square',
    'family nowles',
    'family oakfields',
    'family observatory',
    'family odensdaalsrus',
    'family oudtshoorn',
    'family pacaltsdorp',
    'family panorama',
    'family parow',
    'family parys',
    'family phalaborwa',
    'family philipi junction',
    'family piet retief',
    'family pine ridge',
    'family pioneer park',
    'family pongola',
    'family port alfred',
    'family port shepstone',
    'family postmasburg',
    'family preller walk mall',
    'family protea boulevard',
    'family protea north',
    'family queenstown',
    'family rayton',
    'family reizis',
    'family reyno ridge',
    'family rhodesdene',
    'family riebeek wes',
    'family river crescent',
    'family robertson',
    'family rondebosch',
    'family sable square',
    'family sandridge square',
    'family sasolburg',
    'family secunda',
    'family sedgefield',
    'family sherwood',
    'family simons town',
    'family sky city',
    'family songloed',
    'family soshanguve crossing',
    'family springs gate',
    'family st. johns village',
    'family standerton',
    'family standerton cbd',
    'family stanger',
    'family steelpoort',
    'family steenberg',
    'family strand street',
    'family strubenvale',
    'family struisbaai liquor',
    'family stutterheim',
    'family summerfields boskruin',
    'family swellengrebel',
    'family tembisa',
    'family tembisa megamart',
    'family thaba mall',
    'family the galleria',
    'family the gardens',
    'family the reeds',
    'family the verge',
    'family towers',
    'family towers at langenhoven',
    'family umhlanga',
    'family umtata',
    'family upington',
    'family vanderbijl',
    'family vanderbijl park',
    'family vanderhof park',
    'family verulam',
    'family vredenburg',
    'family vryburg',
    'family vryheid',
    'family walker drive',
    'family warmbaths',
    'family waverly',
    'family welkom',
    'family wellington',
    'family westonaria',
    'family whiteriver',
    'family wilro park',
    'family witbank',
    'family witpoortjie',
    'family wolmaransstad',
    'family wonderboom junction',
    'family woodlands boulevard',
    'family york street',
    'family zeerust',
    'festival mall',
    'florida',
    'fourways',
    'fourways mall',
    'gallo manor',
    'garden route mall',
    'gardens',
    'gd41 - local linden',
    'gd44 - merino mall ermelo',
    'gd45 - louis botha',
    'gd46 - primrose',
    'gd47 - goldman',
    'george',
    'glen curve',
    'glen garry',
    'goldman',
    'gonubie',
    'goodwood',
    'grabouw',
    'grassy park',
    'groblersdal',
    'hatfield',
    'hayfields',
    'hazeldean square',
    'hazyview',
    'hermanus',
    'highveld mall',
    'hillcrest boulevard',
    'hilton the avenues',
    'hout bay',
    'hyde park',
    'hyper bloemfontein',
    'hyper boksburg',
    'hyper brackenfell',
    'hyper centurion',
    'hyper durban north',
    'hyper greenstone',
    'hyper klerksdorp',
    'hyper longbeach',
    'hyper moffet park',
    'hyper montana',
    'hyper northgate',
    'hyper norwood',
    'hyper ottery',
    'hyper princess crossing',
    'hyper south coast',
    'hyper soweto',
    'hyper steeledale',
    'hyper wonderpark',
    'hyper woodmead',
    'ilanga mall',
    'irene village mall',
    'jean avenue - centurion',
    'jubilee mall',
    'kenilworth',
    'kenilworth super store',
    'kensington',
    'key west',
    'kilburn',
    'killarney',
    'kimberley',
    'knysna',
    'kroonstad',
    'krugersdorp',
    'kwa-guqa',
    'kwadukuza mall',
    'kwagga plaza',
    'kwamnyandu',
    'kyalami on main',
    'la lucia',
    'ladysmith',
    'lakeside',
    'lakeside mall benoni',
    'langeberg mall',
    'langehoven park',
    'lemo mall mangaung',
    'lenasia',
    'lephalale',
    'liberty midlands mall',
    'local big bay',
    'local bloem plaza',
    'local bloemgate',
    'local bluewater bay',
    'local boston',
    'local epping garden village',
    'local ficksburg',
    'local florida road',
    'local germiston',
    'local golden sun',
    'local halt road',
    'local hendrina',
    'local hibberdene',
    'local kenridge',
    'local klipkop de le ray',
    'local leandra',
    'local leondale',
    'local linden',
    'local lotus river',
    'local monte vista',
    'local mooi river',
    'local moreleta park',
    'local north beach',
    'local northam',
    'local pam golding on main',
    'local petervale',
    'local polokwane crescent',
    'local poppys retreat',
    'local pretoria north',
    'local waterglen',
    'local waterkloof',
    'local welgemoed',
    'local worcester',
    'loch logan',
    'lonehill',
    'longbeach mall',
    'louis botha',
    'lynnwood',
    'mabopane lifestyle',
    'makhado',
    'mall at lebo',
    'mall at reds',
    'mall of africa',
    'mall of the north',
    'mall of the south',
    'maluti crescent',
    'mams mall',
    'margate',
    'matatiele',
    'matlosana mall',
    'mayfield square',
    'meer en see',
    'melkbos',
    'menlyn maine',
    'menlyn mall',
    'middelburg mall',
    'midrand',
    'midwater mall',
    'midway crossing',
    'mini market golf park',
    'mini market henneman',
    'mini market lakefield',
    'mini market oakdene',
    'mini market randfontein',
    'mini market riebeeck kasteel',
    'mini market showgrounds',
    'mini market viljoenskroon',
    'mini market virginia',
    'mmabatho',
    'mokopane mall',
    'montana',
    'montclair',
    'morningside',
    'moruleng',
    'mountain mill',
    'mthatha',
    'muizenberg',
    'musgrave road',
    'n1 city',
    'nelspruit',
    'new redruth',
    'newcastle',
    'newton park',
    'newtown junction',
    'nkomo mall',
    'nonesi mall',
    'noordstad',
    'northlands corner',
    'northmead',
    'olympus',
    'on nicol',
    'one on mutual',
    'outspan road',
    'paarl mall',
    'palm ridge',
    'parklands',
    'parow exchange',
    'pecanwood',
    'phillip nel park',
    'pinehurst',
    'pinelands',
    'pinetown',
    'plantland',
    'plattekloof',
    'plettenberg bay',
    'plumstead',
    'pnp hyper somerset mall',
    'pnp qualisave dobsonville',
    'pnp qualisave groendal',
    'pnp qualisave jabulani mall',
    'pnp qualisave letsheng mall',
    'pnp qualisave local germiston',
    'pnp qualisave parklands juncti',
    'pnp qualisave tshepisong',
    'polokwane',
    'potchefstroom',
    'primrose',
    'promenade',
    'quagga',
    'queensburgh',
    'randburg square',
    'randpark ridge',
    'randsteam',
    'ravenswood',
    'richards bay',
    'richmond corner',
    'ridge terrace',
    'riverside mall',
    'rosebank',
    'rosmead',
    'royldene',
    'ruimsig',
    'rustenburg',
    'sam ntuli',
    'sanbury square',
    'sasolburg',
    'savannah',
    'scottburgh',
    'sea point',
    'sebokeng',
    'secunda mall',
    'shelly beach',
    'sinoville',
    'somerset west',
    'southdale',
    'southdowns',
    'southernwood',
    'southgate',
    'springfield',
    'springs mall',
    'station house',
    'stellenbosch',
    'stellenbosch square',
    'strand',
    'summerstrand',
    'sunningdale',
    'sunward park',
    'table bay mall',
    'tableview',
    'tembisa megamart',
    'thavhani mall',
    'the 3 arts diep river',
    'the bluff',
    'the bridge',
    'the falls',
    'the glen',
    'the grove',
    'the marc',
    'the oaks',
    'the pavilion',
    'the sanctuary strand',
    'the workshop',
    'three rivers',
    'thulamahashe',
    'tokai',
    'tramshed',
    'tshwane mall',
    'tygervalley',
    'tzaneen',
    'uitenhage',
    'uitenhage cbd',
    'umhlanga crescent',
    'umlazi megacity',
    'umphakathi',
    'vaal mall',
    'vangate mall',
    'victory park',
    'vincent park',
    'vosloorus',
    'walmer park',
    'waterfall mall',
    'waterfront',
    'waterstone village',
    'wd15 - zevenview',
    'welkom',
    'weskus mall',
    'westown square',
    'westville junction',
    'westwood',
    'willowbridge',
    'witbank',
    'wonderboom junction',
    'woodlands boulevard',
    'worcester',
    'wynberg',
    'zevenview',
}


import sys
import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'mysite.settings')
django.setup()

from main.models import Client

DRY_RUN = '--dry-run' in sys.argv

if DRY_RUN:
    print('=== DRY RUN MODE (no changes will be saved) ===\n')
else:
    print('=== LIVE MODE (changes will be saved) ===\n')

# Get all PnP clients
pnp_clients = (
    Client.objects.filter(corporate_group__icontains='pick n pay') |
    Client.objects.filter(name__icontains='pick n pay') |
    Client.objects.filter(name__icontains='pnp')
).distinct()

print(f'Found {pnp_clients.count()} PnP clients in database\n')

updates = []
no_match = []

for c in pnp_clients.order_by('name'):
    store_part = c.name.lower()
    store_part = store_part.replace('pick n pay', '').replace('pnp', '').strip()

    if not store_part:
        print(f'  SKIP: {c.name} - no store name to match')
        continue

    in_franchise = store_part in FRANCHISE_STORE_NAMES
    in_corporate = store_part in CORPORATE_STORE_NAMES

    if not in_franchise and not in_corporate:
        for fn in FRANCHISE_STORE_NAMES:
            if store_part in fn or fn in store_part:
                in_franchise = True
                break
        for cn in CORPORATE_STORE_NAMES:
            if store_part in cn or cn in store_part:
                in_corporate = True
                break

    is_franchise_brand = any(tag in store_part for tag in ['family', 'qualisave'])
    is_corporate_brand = 'hyper' in store_part

    old_type = c.group_type
    old_group = c.corporate_group
    new_type = None
    new_group = None

    if is_franchise_brand:
        new_type = 'Franchise Store'
        new_group = 'Pick n Pay - Franchise'
    elif is_corporate_brand:
        new_type = 'Corporate Store'
        new_group = 'Pick n Pay - Corporate'
    elif in_franchise and not in_corporate:
        new_type = 'Franchise Store'
        new_group = 'Pick n Pay - Franchise'
    elif in_corporate and not in_franchise:
        new_type = 'Corporate Store'
        new_group = 'Pick n Pay - Corporate'
    elif in_franchise and in_corporate:
        new_type = 'Corporate Store'
        new_group = 'Pick n Pay - Corporate'
        print(f'  WARNING: {c.name} found in BOTH lists, defaulting to Corporate')
    else:
        no_match.append(c.name)
        print(f'  NO MATCH: {c.name} (searched for "{store_part}")')
        continue

    if old_type != new_type or old_group != new_group:
        print(f'  UPDATE: {c.name} | type: {old_type} -> {new_type} | group: {old_group} -> {new_group}')
        if not DRY_RUN:
            c.group_type = new_type
            c.corporate_group = new_group
            c.save()
        updates.append(c.name)
    else:
        print(f'  OK: {c.name} already correct ({new_type})')

print(f'\n=== SUMMARY ===')
print(f'Total PnP clients checked: {pnp_clients.count()}')
print(f'{"Would update" if DRY_RUN else "Updated"}: {len(updates)}')
for u in updates:
    print(f'  - {u}')
if no_match:
    print(f'No match found: {len(no_match)}')
    for n in no_match:
        print(f'  - {n}')
