# Generated by Django 5.1.7 on 2026-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_client_fk_to_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='corporate_group',
            field=models.CharField(blank=True, help_text='Corporate group (e.g., Pick n Pay, Checkers, Spar)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='facility_type',
            field=models.CharField(blank=True, help_text='Facility type (Retailer, Butchery, Re-Packer, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='group_type',
            field=models.CharField(blank=True, help_text='Group type (Corporate Store, Franchise Store, Individual)', max_length=100, null=True),
        ),
    ]
