# Generated by Django 6.0.1 on 2026-01-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_add_client_classification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='additional_email',
            field=models.CharField(blank=True, help_text='Additional email(s) for this specific inspection group - can be comma-separated', max_length=500, null=True),
        ),
    ]
