# Generated by Django 6.0.1 on 2026-01-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_change_additional_email_to_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='inspection_sequence',
            field=models.IntegerField(default=1, help_text='Sequence number for this inspection within its group (1, 2, 3, etc.)'),
        ),
    ]
