# Generated by Django 6.0.1 on 2026-01-26 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_add_inspection_group'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='foodsafetyagencyinspection',
            name='idx_insp_group',
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='additional_email',
            field=models.EmailField(blank=True, help_text='Additional email for this group', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_groups', to='main.client'),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='client_name',
            field=models.CharField(help_text='Client name', max_length=200),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='comment',
            field=models.TextField(blank=True, help_text='Comment for this group', null=True),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='corporate_group',
            field=models.CharField(blank=True, help_text='Corporate group', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='date_of_inspection',
            field=models.DateField(help_text='Date of inspection'),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='facility_type',
            field=models.CharField(blank=True, help_text='Facility type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='group_type',
            field=models.CharField(blank=True, help_text='Group type', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours worked', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='inspector_name',
            field=models.CharField(blank=True, help_text='Inspector name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='is_manual',
            field=models.BooleanField(default=True, help_text='Manually created (vs synced from server)'),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='km_traveled',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilometers traveled', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='town',
            field=models.CharField(blank=True, help_text='Town/location', max_length=100, null=True),
        ),
    ]
