# Generated by Django 6.0.1 on 2026-01-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_foodsafetyagencyinspection_idx_insp_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='is_manual',
            field=models.BooleanField(default=True, help_text='True if this inspection was manually entered (not synced from SQL Server)'),
        ),
    ]
