# Generated by Django 6.0.1 on 2026-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_is_manual_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiongroup',
            name='travel_end_time',
            field=models.TimeField(blank=True, help_text='Travel end time', null=True),
        ),
        migrations.AddField(
            model_name='inspectiongroup',
            name='travel_start_time',
            field=models.TimeField(blank=True, help_text='Travel start time', null=True),
        ),
    ]
