# Generated by Django 6.0.1 on 2026-02-13 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_inspectiongroup_travel_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='lab',
            field=models.CharField(blank=True, choices=[('lab_a', 'Food Safety Laboratory'), ('lab_b', 'Merieux NutriSciences'), ('lab_c', 'AGRI Food Laboratory (SGS)'), ('lab_d', 'SANBI'), ('lab_e', 'SMT'), ('lab_f', 'ARC')], help_text='Laboratory used for testing', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='InspectorManagerAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_allocations', to='main.inspectormapping')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_inspectors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspector_manager_allocations',
                'unique_together': {('manager', 'inspector_mapping')},
            },
        ),
    ]
