# Generated by Django 6.0.1 on 2026-02-16 21:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_inspectiongroup_travel_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='lab',
            field=models.CharField(blank=True, choices=[('lab_a', 'Food Safety Laboratory'), ('lab_b', 'Merieux NutriSciences'), ('lab_c', 'AGRI Food Laboratory (SGS)'), ('lab_d', 'SANBI'), ('lab_e', 'SMT'), ('lab_f', 'ARC')], help_text='Laboratory used for testing', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['inspection_group'], name='food_safety_inspect_0cea9e_idx'),
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['inspection_group', 'date_of_inspection', 'client_name'], name='food_safety_inspect_ed2994_idx'),
        ),
        migrations.AddIndex(
            model_name='foodsafetyagencyinspection',
            index=models.Index(fields=['is_sent'], name='food_safety_is_sent_2119fb_idx'),
        ),
    ]
