# Generated by Django 6.0.1 on 2026-02-18 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_add_inspection_group_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Who approved this inspection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='approved_date',
            field=models.DateTimeField(blank=True, help_text='When this inspection was approved', null=True),
        ),
    ]
