# Generated by Django 6.0.1 on 2026-02-24 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_add_approved_date_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(help_text='Inspector name matching inspection records', max_length=100, unique=True)),
                ('eggs', models.IntegerField(default=51)),
                ('poultry', models.IntegerField(default=59)),
                ('raw', models.IntegerField(default=63)),
                ('pmp', models.IntegerField(default=54)),
                ('raw_samples', models.IntegerField(default=58)),
                ('pmp_samples', models.IntegerField(default=12)),
                ('total_samples', models.IntegerField(default=70)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspector_targets',
                'ordering': ['inspector_name'],
            },
        ),
    ]
