# Generated by Django 6.0.1 on 2026-02-26 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_inspectortarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # NOTE: The InspectorManagerAllocation model is already created by migration
    # 0016 (CreateModel with the same db_table 'inspector_manager_allocations').
    # This migration was a duplicate CreateModel, which made a fresh `migrate`
    # fail with 'relation "inspector_manager_allocations" already exists'. The
    # model already exists in both the database and the migration state after
    # 0016, so this migration is now intentionally a no-op.
    operations = []
