# Generated by Django 5.2.11 on 2026-03-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_inspectormanagerallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('tenant_id', models.CharField(blank=True, default='', max_length=255)),
                ('tenant_name', models.CharField(blank=True, default='', max_length=255)),
                ('token_type', models.CharField(default='Bearer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xero Token',
            },
        ),
        migrations.CreateModel(
            name='XeroInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_invoice_id', models.CharField(max_length=255, unique=True)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=255)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('contact_id', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('AUTHORISED', 'Authorised'), ('PAID', 'Paid'), ('VOIDED', 'Voided'), ('DELETED', 'Deleted')], default='DRAFT', max_length=20)),
                ('invoice_type', models.CharField(default='ACCREC', max_length=20)),
                ('currency_code', models.CharField(default='ZAR', max_length=10)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('fully_paid_on_date', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, default='', max_length=500)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Xero Invoice',
                'ordering': ['-due_date'],
                'indexes': [models.Index(fields=['status'], name='idx_xero_inv_status'), models.Index(fields=['due_date'], name='idx_xero_inv_due'), models.Index(fields=['contact_name'], name='idx_xero_inv_contact')],
            },
        ),
    ]
