# Generated by Django 5.2.11 on 2026-03-10 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_xerotoken_xeroinvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('eggs', models.IntegerField(default=51)),
                ('poultry', models.IntegerField(default=59)),
                ('raw', models.IntegerField(default=63)),
                ('pmp', models.IntegerField(default=54)),
                ('raw_samples', models.IntegerField(default=58)),
                ('pmp_samples', models.IntegerField(default=12)),
                ('total_samples', models.IntegerField(default=70)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quarterly_revenue_target', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_vehicle_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quarterly_targets',
                'ordering': ['inspector_name', 'year', 'quarter'],
                'unique_together': {('inspector_name', 'year', 'quarter')},
            },
        ),
    ]
