# Generated by Django 5.2.11 on 2026-03-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_foodsafetyagencyinspection_lab_and_more'),
        ('main', '0020_xerotoken_xeroinvoice'),
    ]

    operations = [
    ]
