# Generated by Django 5.1.7 on 2026-03-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_merge_20260306_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('CREATE', 'Create Record'), ('UPDATE', 'Update Record'), ('DELETE', 'Delete Record'), ('VIEW', 'View Page'), ('NAVIGATE', 'Navigate'), ('SYNC', 'Data Sync'), ('SETTINGS', 'Settings Change'), ('USER_MANAGEMENT', 'User Management'), ('PASSWORD_RESET', 'Password Reset'), ('FILE_UPLOAD', 'File Upload'), ('EXPORT', 'Data Export'), ('IMPORT', 'Data Import'), ('SEARCH', 'Search'), ('FILTER', 'Filter'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Information')], max_length=200, verbose_name='Action Type'),
        ),
    ]
