# Generated by Django 6.0.3 on 2026-03-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_increase_systemlog_action_length'),
        ('main', '0023_populate_q1_2026_targets'),
    ]

    operations = [
    ]
