# Generated by Django 6.0.3 on 2026-03-17 19:44

from django.db import migrations


INITIAL_SALARIES = {
    'adams': ('adams', 20000, '2291'),
    'dlamini': ('dlamini', 21000, '2028'),
    'dlisani': ('dlisani', 22256, 'AFSQ1259'),
    'kuntwane': ('kuntwane', 21000, '2208'),
    'kabelo': ('kabelo', 20900, '2209'),
    'manganye': ('manganye', 21000, '2201'),
    'maqina': ('maqina', 21000, '2146'),
    'modiba': ('modiba', 20000, '2284'),
    'mokgothu': ('mokgothu', 20000, '2382'),
    'mpeluza': ('mpeluza', 21000, '2210'),
    'ngongo': ('ngongo', 21000, '2182'),
    'noe': ('noe', 26250, '1821'),
    'ntoyaphi': ('ntoyaphi', 20800, '2242'),
    'sekhotho': ('sekhotho', 20900, '1990'),
    'selone': ('selone', 23929.50, '2005'),
    'steyn': ('steyn', 21735, '1823'),
    'visagie': ('visagie', 36847.14, 'AFSQ1248'),
}


def seed_salaries(apps, schema_editor):
    InspectorSalary = apps.get_model('main', 'InspectorSalary')
    for key, (name, salary, emp_num) in INITIAL_SALARIES.items():
        InspectorSalary.objects.update_or_create(
            inspector_name=name,
            defaults={'monthly_salary': salary, 'employee_number': emp_num},
        )


def reverse_seed(apps, schema_editor):
    InspectorSalary = apps.get_model('main', 'InspectorSalary')
    InspectorSalary.objects.filter(inspector_name__in=INITIAL_SALARIES.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_inspector_salaries'),
    ]

    operations = [
        migrations.RunPython(seed_salaries, reverse_seed),
    ]
