# Generated by Django 6.0.3 on 2026-03-18 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_seed_inspector_salaries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionEditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('inspection', 'Inspection'), ('group', 'Inspection Group')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('client_name', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_inspection', models.DateField(blank=True, null=True)),
                ('inspector_name', models.CharField(blank=True, default='', max_length=100)),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('changes', models.JSONField(default=dict)),
                ('change_count', models.PositiveIntegerField(default=0)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_edits', to=settings.AUTH_USER_MODEL)),
                ('inspection_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_history', to='main.inspectiongroup')),
            ],
            options={
                'db_table': 'inspection_edit_history',
                'ordering': ['-edited_at'],
                'indexes': [models.Index(fields=['inspection_group', '-edited_at'], name='idx_ieh_group_date'), models.Index(fields=['edited_by', '-edited_at'], name='idx_ieh_user_date'), models.Index(fields=['-edited_at'], name='idx_ieh_date')],
            },
        ),
    ]
