# Generated by Django 6.0.3 on 2026-03-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_clientdropdownoption'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inspectiongroup',
            index=models.Index(fields=['client_name', 'date_of_inspection', 'inspector_name'], name='idx_group_dup_check'),
        ),
    ]
