# Generated by Django 6.0.4 on 2026-05-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_add_dup_check_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Manual entry of hours worked', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='foodsafetyagencyinspection',
            name='is_product_compliant',
            field=models.BooleanField(default=None, help_text='Product compliance status — NULL = not yet assessed, True = compliant, False = non-compliant', null=True),
        ),
        migrations.AlterField(
            model_name='inspectiongroup',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hours worked', max_digits=8, null=True),
        ),
    ]
