# Generated by Django 6.0.4 on 2026-05-20 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_make_is_product_compliant_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('rfi', 'RFI'), ('invoice', 'Invoice'), ('coa', 'COA'), ('lab_form', 'Lab Form'), ('retest', 'Retest'), ('occurrence', 'Occurrence'), ('composition', 'Composition'), ('compliance', 'Compliance'), ('other', 'Other')], db_index=True, help_text='Type of document uploaded', max_length=20)),
                ('uploaded_date', models.DateTimeField(help_text='When this document was uploaded')),
                ('inspection', models.ForeignKey(help_text='The inspection this document belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.foodsafetyagencyinspection')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection_documents',
                'ordering': ['-uploaded_date'],
                'indexes': [models.Index(fields=['document_type'], name='inspection__documen_8740fa_idx'), models.Index(fields=['inspection', 'document_type'], name='inspection__inspect_64598f_idx')],
                'unique_together': {('inspection', 'document_type')},
            },
        ),
    ]
