# Generated by Django 6.0.4 on 2026-05-20 09:47

from django.db import migrations


def populate_inspection_documents(apps, schema_editor):
    """Populate InspectionDocument from existing upload fields on FoodSafetyAgencyInspection."""
    Inspection = apps.get_model('main', 'FoodSafetyAgencyInspection')
    InspectionDocument = apps.get_model('main', 'InspectionDocument')

    # Map: (document_type, uploaded_by_field, uploaded_date_field)
    field_map = [
        ('rfi', 'rfi_uploaded_by_id', 'rfi_uploaded_date'),
        ('invoice', 'invoice_uploaded_by_id', 'invoice_uploaded_date'),
        ('coa', 'coa_uploaded_by_id', 'coa_uploaded_date'),
        ('lab_form', 'lab_form_uploaded_by_id', 'lab_form_uploaded_date'),
        ('retest', 'retest_uploaded_by_id', 'retest_uploaded_date'),
        ('occurrence', 'occurrence_uploaded_by_id', 'occurrence_uploaded_date'),
        ('composition', 'composition_uploaded_by_id', 'composition_uploaded_date'),
        ('other', 'other_uploaded_by_id', 'other_uploaded_date'),
    ]

    docs_to_create = []
    for doc_type, by_field, date_field in field_map:
        # Only get inspections where this document type has been uploaded
        inspections = Inspection.objects.filter(
            **{f'{date_field}__isnull': False}
        ).values_list('id', by_field, date_field)

        for insp_id, user_id, upload_date in inspections:
            docs_to_create.append(InspectionDocument(
                inspection_id=insp_id,
                document_type=doc_type,
                uploaded_by_id=user_id,
                uploaded_date=upload_date,
            ))

    # Bulk create in batches
    if docs_to_create:
        InspectionDocument.objects.bulk_create(docs_to_create, batch_size=500, ignore_conflicts=True)
        print(f"Created {len(docs_to_create)} InspectionDocument records")


def reverse_migration(apps, schema_editor):
    """Remove all auto-populated InspectionDocument records."""
    InspectionDocument = apps.get_model('main', 'InspectionDocument')
    InspectionDocument.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_create_inspection_document'),
    ]

    operations = [
        migrations.RunPython(populate_inspection_documents, reverse_migration),
    ]
