# Generated by Django 6.0.4 on 2026-05-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetyagencyinspection',
            name='sent_by_name',
            field=models.CharField(blank=True, default='', help_text='Name of user who sent documents (persists after user deletion)', max_length=150),
        ),
    ]
