# Generated by Django 6.0.4 on 2026-05-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_add_sent_by_name_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateGroupEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_group', models.CharField(db_index=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corporate_group_emails',
                'ordering': ['corporate_group', 'email'],
                'unique_together': {('corporate_group', 'email')},
            },
        ),
    ]
