# Generated by Django 6.0.6 on 2026-07-06 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_corporategroupemail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector_name', models.CharField(help_text='Inspector who should have recorded the sample', max_length=100)),
                ('client_name', models.CharField(blank=True, help_text='Client / facility', max_length=200)),
                ('date_of_inspection', models.DateField(blank=True, help_text='Date the inspection was done', null=True)),
                ('commodity', models.CharField(blank=True, help_text='Sample commodity / type', max_length=50)),
                ('note', models.TextField(blank=True, help_text="Lab technician's note")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rectified', models.BooleanField(db_index=True, default=False)),
                ('rectified_at', models.DateTimeField(blank=True, null=True)),
                ('rectified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectified_discrepancies', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_discrepancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sample_discrepancies',
                'ordering': ['-created_at'],
            },
        ),
    ]
