# Generated by Django 6.0.6 on 2026-07-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_samplediscrepancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplediscrepancy',
            name='inspection_group_id',
            field=models.CharField(blank=True, db_index=True, help_text='The inspection group (visit) this flag is against', max_length=50),
        ),
        migrations.AlterField(
            model_name='samplediscrepancy',
            name='inspector_name',
            field=models.CharField(blank=True, help_text='Inspector who should have recorded the sample', max_length=100),
        ),
    ]
