# Generated by Django 6.0.6 on 2026-07-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_samplediscrepancy_inspection_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='session_timeout',
            field=models.IntegerField(default=720, help_text='Session idle timeout in minutes (default 12h)'),
        ),
    ]
