# Generated by Django 6.0.6 on 2026-07-15 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_settings_session_timeout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiongroup',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who captured this inspection group in APS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiongroup',
            name='created_by_name',
            field=models.CharField(blank=True, default='', help_text='Name of the user who captured this group (persists after user deletion)', max_length=150),
        ),
    ]
