# Generated by Django 6.0.6 on 2026-07-27 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_client_approval_status_client_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typed_name', models.CharField(help_text='Client name exactly as the inspector captured it', max_length=200)),
                ('final_name', models.CharField(help_text="Client name after the decision (target client's name for merges)", max_length=200)),
                ('outcome', models.CharField(choices=[('accepted', 'Accepted as new client'), ('merged', 'Matched to existing client')], db_index=True, max_length=20)),
                ('inspector_name', models.CharField(blank=True, default='', max_length=150)),
                ('decided_by_name', models.CharField(blank=True, default='', max_length=150)),
                ('inspection_count', models.IntegerField(default=0, help_text='Inspections attached at decision time')),
                ('client_created_at', models.DateTimeField(blank=True, help_text='When the inspector created the client', null=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('inspector', models.ForeignKey(blank=True, help_text='User whose capture created the client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_approval_entries', to=settings.AUTH_USER_MODEL)),
                ('target_client', models.ForeignKey(blank=True, help_text='Existing client the entry was merged into (merges only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_merges', to='main.client')),
            ],
            options={
                'verbose_name': 'Client Approval Log Entry',
                'verbose_name_plural': 'Client Approval Log',
                'db_table': 'client_approval_log',
                'ordering': ['-decided_at'],
            },
        ),
    ]
