# Generated by Django 6.0.6 on 2026-07-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_clientapprovallog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED_OFF', 'Skipped — switch off'), ('NO_RECIPIENTS', 'Skipped — no active recipients'), ('ALREADY_SENT', 'Skipped — already sent for this week'), ('TEST', 'Test send')], db_index=True, max_length=20)),
                ('recipients', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('triggered_by', models.CharField(blank=True, default='schedule', max_length=150)),
            ],
            options={
                'db_table': 'weekly_email_log',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyEmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('active', models.BooleanField(default=True, help_text='Off = stays on the list but gets no emails')),
                ('added_by', models.CharField(blank=True, default='', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weekly_email_recipients',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyEmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Master switch — OFF means the Monday email never sends')),
                ('subject', models.CharField(default='Weekly Inspectorate Performance Report — {week}', max_length=255)),
                ('body', models.TextField(default='Good day,\n\nPlease find attached the Weekly Inspectorate Performance Report for {week}.\n\nSummary for the week:\n- Inspections completed: {inspections}\n- Overall compliance: {compliance}\n- Samples taken: {samples}\n- Kilometres travelled: {km}\n\nThis report contains no financial information.\n\nRegards,\nAPS System')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'weekly_email_settings',
            },
        ),
    ]
