# Generated by Django 6.0.6 on 2026-07-31 19:02

import django.db.models.deletion
from django.db import migrations, models


def create_default_automation(apps, schema_editor):
    """Carry the old single-email settings over as the first automation.
    The switch deliberately starts OFF — nothing sends until management
    turns it on."""
    EmailAutomation = apps.get_model('main', 'EmailAutomation')
    WeeklyEmailSettings = apps.get_model('main', 'WeeklyEmailSettings')
    WeeklyEmailLog = apps.get_model('main', 'WeeklyEmailLog')
    WeeklyEmailRecipient = apps.get_model('main', 'WeeklyEmailRecipient')

    old = WeeklyEmailSettings.objects.first()
    a = EmailAutomation.objects.create(
        name='Management weekly report',
        enabled=False,
        subject=old.subject if old else EmailAutomation._meta.get_field('subject').default,
        body=old.body if old else EmailAutomation._meta.get_field('body').default,
        updated_by=old.updated_by if old else '',
    )
    WeeklyEmailLog.objects.filter(automation__isnull=True).update(automation=a, automation_name=a.name)
    WeeklyEmailRecipient.objects.filter(automation__isnull=True).update(automation=a)


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_weeklyemaillog_weeklyemailrecipient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="What this email is for, e.g. 'Management weekly report'", max_length=120)),
                ('enabled', models.BooleanField(default=False, help_text='OFF means this email never sends')),
                ('subject', models.CharField(default='Weekly Inspectorate Performance Report — {week}', max_length=255)),
                ('body', models.TextField(default='Good day,\n\nPlease find attached the Weekly Inspectorate Performance Report for {week}.\n\nSummary for the week:\n- Inspections completed: {inspections}\n- Overall compliance: {compliance}\n- Samples taken: {samples}\n- Kilometres travelled: {km}\n\nThis report contains no financial information.\n\nRegards,\nAPS System')),
                ('updated_by', models.CharField(blank=True, default='', max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_automations',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='weeklyemaillog',
            name='automation_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='weeklyemailrecipient',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AddField(
            model_name='weeklyemaillog',
            name='automation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='main.emailautomation'),
        ),
        migrations.AddField(
            model_name='weeklyemailrecipient',
            name='automation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='main.emailautomation'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyemailrecipient',
            unique_together={('automation', 'email')},
        ),
        migrations.RunPython(create_default_automation, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='WeeklyEmailSettings',
        ),
    ]
