# Generated by Django 6.0.6 on 2026-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_emailautomation_delete_weeklyemailsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailautomation',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional extra file sent along with the report PDF', null=True, upload_to='email_automation_attachments/'),
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='schedule_type',
            field=models.CharField(choices=[('weekly', 'Weekly on a day'), ('daily', 'Every day'), ('monthly', 'Monthly on a date')], default='weekly', max_length=10),
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='send_day_of_month',
            field=models.IntegerField(default=1, help_text='1-28 (monthly schedule)'),
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='send_day_of_week',
            field=models.IntegerField(default=0, help_text='0=Monday ... 6=Sunday (weekly schedule)'),
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='send_hour',
            field=models.IntegerField(default=12, help_text='Hour of the day 0-23'),
        ),
        migrations.AddField(
            model_name='emailautomation',
            name='signature',
            field=models.TextField(blank=True, default='', help_text='Added to the end of every email from this automation'),
        ),
    ]
