# Generated by Django 6.0.6 on 2026-07-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_emailautomation_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailautomation',
            name='signature_image',
            field=models.FileField(blank=True, help_text='Optional picture signature shown at the end of the email', null=True, upload_to='email_automation_signatures/'),
        ),
    ]
