# Generated by Django 6.0.6 on 2026-07-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_emailautomation_signature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailautomation',
            name='per_inspector',
            field=models.BooleanField(default=False, help_text='Individual report: each recipient gets an email with ONLY their own numbers'),
        ),
    ]
